create table if not exists public.spm_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

insert into public.spm_categories (name)
values
  ('Operasional Kantor'),
  ('Kegiatan Organisasi'),
  ('Administrasi'),
  ('Perjalanan Dinas'),
  ('Honorarium'),
  ('Rapat / Pertemuan'),
  ('Lain-lain')
on conflict (name) do nothing;

alter table public.spm_categories enable row level security;

drop policy if exists "spm_categories_admin_full" on public.spm_categories;
create policy "spm_categories_admin_full" on public.spm_categories
for all
using (public.current_app_role() = 'admin')
with check (public.current_app_role() = 'admin');

drop policy if exists "spm_categories_bendahara_read" on public.spm_categories;
create policy "spm_categories_bendahara_read" on public.spm_categories
for select
using (public.current_app_role() = 'bendahara');

drop policy if exists "spm_categories_ketua_read" on public.spm_categories;
create policy "spm_categories_ketua_read" on public.spm_categories
for select
using (public.current_app_role() = 'ketua');